/****** Object:  Table [dbo].[CUSTOMER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CUSTOMER](
	[CUST_CODE] [varchar](6) NOT NULL,
	[CUST_NAME] [varchar](40) NOT NULL,
	[CUST_CITY] [char](35) NULL,
	[WORKING_AREA] [varchar](35) NOT NULL,
	[CUST_COUNTRY] [varchar](20) NOT NULL,
	[GRADE] [numeric](18, 0) NULL,
	[OPENING_AMT] [numeric](12, 2) NOT NULL,
	[RECEIVE_AMT] [numeric](12, 2) NOT NULL,
	[PAYMENT_AMT] [numeric](12, 2) NOT NULL,
	[OUTSTANDING_AMT] [numeric](12, 2) NOT NULL,
	[PHONE_NO] [varchar](10) NULL,
	[AGENT_CODE] [char](6) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CUST_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[CUSTOMER]  WITH CHECK ADD FOREIGN KEY([AGENT_CODE])
REFERENCES [dbo].[AGENTS] ([AGENT_CODE])
